var paper_data = [
    {
        img: 'assets/img/journal/nat-commu.jpg',
        title: 'Overcoming small-bandgap charge recombination in visible and NIR-light-driven hydrogen evolution by engineering the polymer photocatalyst structure',
        author:'Mohamed Hammad Elsayed, Mohamed Abdellah, Ahmed Zaki Alhakemy, Islam M. A. Mekhemer, Ahmed Esmail A. Aboubakr, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Amr Sabbah, Kun-Han Lin, Wen-Sheng Chiu, Sheng-Jie Lin, Che-Yi Chu, Chih-Hsuan Lu, Shang-Da Yang, Mohamed Gamal Mohamed, Shiao-Wei Kuo, Chen-Hsiung Hung, Li-Chyong Chen, Kuei-Hsien Chen and Ho-Hsiu Chou',
        journal: 'Nature Communications',
        volume: '15',
        issue: '707',
        page: '',
        year: '2024',
        published: true,
        link: 'https://doi.org/10.1038/s41467-024-45085-6'
    },
    {
        img: 'assets/img/journal/angew-chem-v63-16.jpg',
        title: 'Singlet Fission in a New Series of Systematically Designed Through-space Coupled Tetracene Oligomers',
        author:'Maciej Majdecki, Chao-Hsien Hsu, Chih-Hsing Wang, Emily Hsue-Chi Shi, Magdalena Zakrocka, Yu-Chen Wei, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Chih-Hsuan Lu, Shang-Da Yang, Pi-Tai Chou and Przemysław Gaweł',
        journal: 'Angewandte Chemie',
        volume: '63',
        issue: '10',
        page: 'e202401103',
        year: '2024',
        published: true,
        link: 'https://doi.org/10.1002/anie.202401103'
    },
    {
        img: 'assets/img/journal/chem-eur-j-v30-8.webp',
        title: 'A New Series of Sandwich-Type 5,5′-Biterphenylenes: Synthetic Challenge, Structural Uniqueness and Photodynamics',
        author:'Ming-Lun Pan, Chao-Hsien Hsu, Yan-Ding Lin, Wei-Sen Chen, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Chih-Hsuan Lu, Shang-Da Yang, Mu-Jeng Cheng, Pi-Tai Chou and Yao-Ting Wu',
        journal: 'Chemistry A European Journal',
        volume: '30',
        issue: '10',
        page: 'e202303523',
        year: '2024',
        published: true,
        link: 'https://doi.org/10.1002/chem.202303523'
    },
    {
        img: 'assets/img/journal/small-v19-46.jpg',
        title: 'Highly Efficient MAPbI3-based Quantum Dots Exhibiting Unusual Nonblinking Single Photon Emission at Room Temperature',
        author:'Yung-Tang Chuang, Tzu-Yu Lin, Guang-Hsun Tan, Pei-En Jan, Hao-Cheng Lin, Hung-Ming Chen, Kai-Yuan Hsiao, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Chih-Hsuan Lu, Chi-Hsuan Lee, Chun-Wei Pao, Shang-Da Yang, Ming-Yen Lu, Hao-Wu Lin',
        journal: 'Small',
        volume: '20',
        issue: '',
        page: '2308676',
        year: '2023',
        published: true,
        link: 'https://doi.org/10.1002/smll.202308676'
    },
    {
        img: 'assets/img/journal/small-v19-45.jpg',
        title: 'Performance and Solution Structures of Side-Chain-Bridged Oligo (Ethylene Glycol) Polymer Photocatalysts for Enhanced Hydrogen Evolution under Natural Light Illumination',
        author:'Tse-Fu Huang,  Jia-Jen Liu,  Ze-Yu Lai,  Je-Wei Chang,  Ying-Rang Zhuang,  Zi-Cheng Jiang,  Chih-Li Chang,  Wei-Cheng Lin,  Yan-Heng Chen,  Yi-Hsiang Wu,  Yu-En Sun,  Ting-An Luo,  Yi-Kuan Chen,  Jui-Chen Yen,  Hung-Kai Hsu,  <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>,  Li-Yu Ting,  Chia-Yeh Lu,  Yu-Tung Lin,  Ling-Yu Hsu,  Tien-Lin Wu,  Shang-Da Yang,  An-Chung Su,  U-Ser Jeng, and  Ho-Hsiu Chou',
        journal: 'Small',
        volume: '20',
        issue: '',
        page: '2304743',
        year: '2023',
        published: true,
        link: 'https://doi.org/10.1002/smll.202304743'
    },
    {
        img: 'assets/img/journal/adv-sci-v10-31.jpg',
        title: 'Semi-Transparent, Pixel-Free Upconversion Goggles withDual Audio-Visual Communication',
        author:'Chun-Jen Shih, Chao-Yang Lin, Kai Chen, Nurul Ridho Al Amin, Dian Luo, I-Sheng Hsu,Abdul Khalik Akbar, Sajal Biring, Chih-Hsuan Lu, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Shang-Da Yang, Jiun-Haw Lee, and Shun-Wei Liu',
        journal: 'Advanced Science',
        volume: '10',
        issue: '31',
        page: '2302631',
        year: '2023',
        published: true,
        link: 'https://doi.org/10.1002/advs.202302631'
    },
    {
        img: 'assets/img/journal/angew-chem-v62-40.jpg',
        title: 'Self-Assembled Monolayers of Bi-Functionalized Porphyrins: A Novel Class of Hole-Layer-Coordinating Perovskites and Indium Tin Oxide in Inverted Solar Cells',
        author:'Chieh-Ming Hung, Chi-Lun Mai, Chi-Chi Wu, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Chih-Hsuan Lu, Che-Chun Chu, Meng-Chuan Wang, Shang-Da Yang, Hsieh-Chih Chen, Chen-Yu Yeh, and Pi-Tai Chou',
        journal: 'Angewandte Chemie International Edition',
        volume: '62',
        issue: '40',
        page: 'e202309831',
        year: '2023',
        published: true,
        link: 'https://doi.org/10.1002/anie.202309831'
    },
    {
        img: 'assets/img/journal/nat-commu.jpg',
        title: 'Synthesis, structural analysis, and properties of highly twisted alkenes 13,13’-bis(dibenzo[a,i]fluorenylidene) and its derivatives',
        author:'Hao-Wen Kang, Yu-Chiao Liu, Wei-Kai Shao, Yu-Chen Wei, Chi-Tien Hsieh, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Chih-Hsuan Lu, Shang-Da Yang, Mu-Jeng Cheng, Pi-Tai Chou, Ming-Hsi Chiang, and Yao-Ting Wu',
        journal: 'Nature Communications',
        volume: '14',
        issue: '5248',
        page: '',
        year: '2023',
        published: true,
        link: 'https://doi.org/10.1038/s41467-023-40990-8'
    },
    {
        img: 'assets/img/journal/journal-physical-chemistry-b-v127-31.jpg',
        title: 'Electronic Preresonance Stimulated Raman Scattering Spectromicroscopy Using Multiple-Plate Continuum',
        author:'Guan-Jie Huang, Cheng-Wei Li, Po-Yi Lee, Jia-Xuan Su, Kuo-Chuan Chao, Li-An Chu, Ann-Shyn Chiang, Ji-Xin Cheng, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Chih-Hsuan Lu, Shi-Wei Chu, and Shang-Da Yang',
        journal: 'The Journal of Physical Chemistry B',
        volume: '127',
        issue: '31',
        page: '6896–6902',
        year: '2023',
        published: true,
        link: 'https://doi.org/10.1021/acs.jpcb.3c02629'
    },
    {
        img: 'assets/img/journal/angew-chem-v62-16.jpg',
        title: 'Excited-State THz Vibrations in Aggregates of PtII Complexes Contribute to the Enhancement of Near-Infrared Emission Efficiencies',
        author:'Yu-Chen Wei, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Ren-Siang Ye, Hsing-Wei Huang, Jia-Xuan Su, Chao-Yang Lin, Justin Hodgkiss, Lian-Yan Hsu, Yun Chi, Kai Chen, Chih-Hsuan Lu, Shang-Da Yang and Pi-Tai Chou',
        journal: 'Angewandte Chemie International Edition',
        volume: '62',
        issue: '16',
        page: 'e202300815',
        year: '2023',
        published: true,
        link: 'https://onlinelibrary.wiley.com/doi/10.1002/anie.202300815'
    },
    {
        img: 'assets/img/journal/adv-sci-v10-4.jpg',
        title: 'Vacuum-Deposited Inorganic Perovskite Light-Emitting Diodes with External Quantum Efficiency Exceeding 10% via Composition and Crystallinity Manipulation of Emission Layer under High Vacuum',
        author:'Chung-An Hsieh, Guang-Hsun Tan, Yung-Tang Chuang, Hao-Cheng Lin, Po-Ting Lai, Pei-En Jan, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Chih-Hsuan Lu, Shang-Da Yang, Kai-Yuan Hsiao, Ming-Yen Lu, Li-Yin Chen, Hao-Wu Lin',
        journal: 'Advanced Science',
        volume: '10',
        issue: '10',
        page: '2206076',
        year: '2023',
        published: true,
        link: 'https://doi.org/10.1002/advs.202206076'
    },
    {
        img: 'assets/img/journal/opt-express.jpg',
        title: 'Towards Stimulated Raman Scattering Spectro-Microscopy Across the Entire Raman Active Region Using Multiple-plate Continuum',
        author:'Guan-Jie Huang, Pei-Chen Lai, Ming-Wei Shen, Jia-Xuan Su, Jhan-Yu Guo, Kuo-Chuan Chao, Peng Lin, Ji-Xin Cheng, Li-An Chu, Ann-Shyn Chiang, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Chih-Hsuan Lu, Shi-Wei Chu and Shang-Da Yang',
        journal: 'Optics Express',
        volume: '30',
        issue: '21',
        page: '38975-38984',
        year: '2022',
        published: true,
        link: 'https://opg.optica.org/oe/fulltext.cfm?uri=oe-30-21-38975&id=509741'
    },
    {
        img: 'assets/img/journal/annalen-der-physik.webp',
        title: 'Free-electron tomography of few-cycle optical waveforms',
        author:'Yuya Morimoto, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span> and Peter Baum',
        journal: 'Annalen der Physik',
        volume: '534',
        issue: '9',
        page: '2200193',
        year: '2022',
        published: true,
        link: 'https://doi.org/10.1002/andp.202200193'
    },
    {
        img: 'assets/img/journal/opt-lett.jpg',
        title: 'Vortex beam assisted energy up-scaling for multiple-plate compression with a single spiral phase plate',
        author:'<span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen*</u></span>, Hsing-Wei Huang, Ren-Siang Ye, Chih-Hsuan Lu, Kai Chen, and Shang-Da Yang',
        journal: 'Optics Letters',
        volume: '47',
        issue: '17',
        page: '4423-4426',
        year: '2022',
        published: true,
        link: 'https://opg.optica.org/ol/fulltext.cfm?uri=ol-47-17-4423&id=495634'
    },
    {
        img: 'assets/img/journal/no-cover.png',
        title: 'Double-Pass Multiple-Plate Continuum for High-Temporal-Contrast Nonlinear Pulse Compression',
        author:'<span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Jia-Xuan Su, Jhan-Yu Guo, Kai Chen, Shi-Wei Chu, Hsuan-Hao Lu, Chih-Hsuan Lu and Shang-Da Yang',
        journal: 'Frontiers in Photonics',
        volume: '3',
        issue: false,
        page: '937622',
        year: '2022',
        published: true,
        link: 'https://www.frontiersin.org/articles/10.3389/fphot.2022.937622/full'
    },
    {
        img: 'assets/img/journal/optica2021.jpg',
        title: 'Asymmetric single-cycle control of valence electron motion in polar chemical bonds',
        author:'Yuya Morimoto, Yasushi Shinohara, Mizuki Tani, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Kenichi L. Ishikawa, and Peter Baum',
        journal: 'Optica',
        volume: '8',
        issue: '3',
        page: '382-387',
        year: '2021',
        published: true,
        link: 'https://opg.optica.org/optica/fulltext.cfm?uri=optica-8-3-382&id=449179'
    },
    {
        img: 'assets/img/journal/journal-physics-b.gif',
        title: 'Broadband terahertz solid-state emitter driven by Yb:YAG thin-disk oscillator',
        author:'Gaia Barbiero, Haochuan Wang, Jonathan Brons, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Vladimir Pervak and Hanieh Fattahi',
        journal: 'Journal of Physics B: Atomic, Molecular and Optical Physics',
        volume: '53',
        issue: '12',
        page: '125601',
        year: '2021',
        published: true,
        link: 'https://iopscience.iop.org/article/10.1088/1361-6455/ab8049/meta'
    },
    {
        img: 'assets/img/journal/opt-lett.jpg',
        title: 'Second-harmonic generation and self-phase modulation of few-cycle mid-infrared pulses',
        author:'<span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Christina Hofer, Ioachim Pupeza, and Peter Baum',
        journal: 'Optics Letters',
        volume: '44',
        issue: '16',
        page: '4079-4082',
        year: '2019',
        published: true,
        link: 'https://opg.optica.org/ol/fulltext.cfm?uri=ol-44-16-4079&id=416698'
    },
    {
        img: 'assets/img/journal/opt-express.jpg',
        title: 'Octave-spanning single-cycle middle-infrared generation through optical parametric amplification in LiGaS<sub>2</sub>',
        author:'<span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Emanuel Wittmann, Yuya Morimoto, Peter Baum, and Eberhard Riedle',
        journal: 'Optics Express',
        volume: '27',
        issue: '15',
        page: '21306-21318',
        year: '2019',
        published: true,
        link: 'https://opg.optica.org/oe/fulltext.cfm?uri=oe-27-15-21306&id=415515'
    },
    {
        img: 'assets/img/journal/opt-lett.jpg',
        title: 'Efficient middle-infrared generation in LiGaS<sub>2</sub> by simultaneous spectral broadening and difference-frequency generation',
        author:'<span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Tamas Nagy, and Peter Baum',
        journal: 'Optics Letters',
        volume: '43',
        issue: '8',
        page: '1742-1745',
        year: '2018',
        published: true,
        link: 'https://opg.optica.org/ol/fulltext.cfm?uri=ol-43-8-1742&id=385370'
    },
    {
        img: 'assets/img/journal/opt-express.jpg',
        title: 'Compression of picosecond pulses from a thin-disk laser to 30fs at 4W average power',
        author:'<span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Martin Kretschmar, Dominik Ehberger, Andreas Blumenstein, Peter Simon, Peter Baum, and Tamas Nagy',
        journal: 'Optics Express',
        volume: '26',
        issue: '4',
        page: '3861-3869',
        year: '2018',
        published: true,
        link: 'https://opg.optica.org/oe/fulltext.cfm?uri=oe-26-4-3861&id=381423'
    },
    {
        img: 'assets/img/journal/optica2014.jpg',
        title: 'Generation of intense supercontinuum in condensed media',
        author:'Chih-Hsuan Lu, Yu-Jung Tsou, Hong-Yu Chen, <span style="color: rgb(31, 85, 143);"><u>Bo-Han Chen</u></span>, Yu-Chen Cheng, Shang-Da Yang, Ming-Chang Chen, Chia-Chen Hsu, and A. H. Kung',
        journal: 'Optica',
        volume: '1',
        issue: '6',
        page: '400-406',
        year: '2014',
        published: true,
        link: 'https://opg.optica.org/optica/fulltext.cfm?uri=optica-1-6-400&id=306182'
    },
]